name: Deploy Bot to Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/chensl/ai-bot-production-v2.1
          git pull origin master
          npm install --only=production
          
          # 优雅重启机器人
          if pgrep -f "advanced-bot.js" > /dev/null; then
            echo "停止现有机器人..."
            pkill -f "advanced-bot.js"
            sleep 3
          fi
          
          echo "启动机器人..."
          nohup node advanced-bot.js > bot.log 2>&1 &
          
          echo "部署完成！"
          sleep 2
          
          # 验证机器人启动
          if pgrep -f "advanced-bot.js" > /dev/null; then
            echo "✅ 机器人启动成功"
          else
            echo "❌ 机器人启动失败"
            exit 1
          fi